name: "profashion"

services:

  nginx:
    container_name: nginx
    hostname: nginx
    build:
      context: ./docker/nginx/
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8988:80"
    depends_on:
      - php
      - db
    networks:
      - test-network

  php:
    container_name: php
    hostname: php
    build:
      context: ./docker/php/
    volumes:
      - ./:/app:delegated
    environment:
      APP_LOCALE: en
    depends_on:
      - db
    networks:
      - test-network

  db:
    container_name: db
    hostname: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mysql/init-db:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_SERVER_FORWARD_PORT:-53346}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-profashion}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
    networks:
      - test-network


volumes:
  mysql: {}

networks:
  test-network:
    name: test-network
